import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavbarHeader from "@/components/navbar-header";
import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/client";
import { AgentJobsProvider } from "@/features/billing/contexts/agent-jobs-context";

const roboto = Roboto({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <TRPCReactProvider>
        <html
          lang="en"
          className={cn("h-full", "antialiased", roboto.variable)}
          suppressHydrationWarning
        >
          <body className="min-h-screen flex flex-col">
            <AgentJobsProvider>
              <NavbarHeader />
              <main className="flex-1 flex flex-col">{children}</main>
              <Toaster />
            </AgentJobsProvider>
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
